[feat] getLatestScheduleByTeacher
Gwasuwon-shot/Tutice_Server pull request #78
Opened 2023-07-18 17:26 UTC by sojungpp

### 🌳 이슈 번호

---

closes #75 

<br/>

### ☀️ 어떻게 이슈를 해결했나요?

---

<br/>

### ❄️ 주의할 점

---
scheduleResponse에서 공통으로 쓰이는 dto가 있는데 클래스명을 맨 처음 지은걸로 사용하고 있어서 추후 공통 클래스명으로 수정하겠습니다 (메모)

2023-07-18 17:46 UTC, YuSuhwa-ve requested changes

2023-07-18 17:46 UTC, YuSuhwa-ve commented on src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleByTime.java
> +public class ScheduleByTime {
오오 공통사용 아주 좋아용

2023-07-18 17:46 UTC, YuSuhwa-ve commented on src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
> +        boolean isMissingMaintenance = scheduleRepository.existsByLessonInAndStatusNotOrderByDateDesc(lessonList, ScheduleStatus.NO_STATUS);
이거 로직 내가 잘못생각함.... 
레포에서 가져올때 No_Status가 아닌걸 가져오는게아니라 Cancle이 아닌것만 가져와서 레포에서 가져온 스케쥴이 no_Status이면 연장이 필요한것(아직 연장안함)이야!

2023-07-18 17:47 UTC, YuSuhwa-ve commented on src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
> +        boolean isMissingMaintenance = scheduleRepository.existsByLessonInAndStatusNotOrderByDateDesc(lessonList, ScheduleStatus.NO_STATUS);
lesson list 한번에 LessonIn 넣은거 넘 좋다!

2023-07-18 17:50 UTC, YuSuhwa-ve approved these changes

2023-07-18 18:28 UTC, sojungpp commented on src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
> +        boolean isMissingMaintenance = scheduleRepository.existsByLessonInAndStatusNotOrderByDateDesc(lessonList, ScheduleStatus.NO_STATUS);
아아세상ㅇㅔ !!!!! 수정했습니닷

2023-07-19 06:01 UTC, YuSuhwa-ve commented on src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
> +        boolean isMissingMaintenance = scheduleRepository.existsByLessonInAndStatusNot(lessonList, ScheduleStatus.CANCEL);
소정... 어제 아리까리한 상태에서 리뷰남겨서 꼬인듯....

> isMissingMaintenance = scheduleRepository.existsByLessonInAndStatusNot(lessonList, ScheduleStatus.CANCEL);

를 

`isMissingMaintenance = scheduleRepository.existsByLessonInAndStatusNot(lessonList, ScheduleStatus.NO_STATUS);`
인게 맞는듯!!
어차피 유저가 가진 종료하지 않은 수업에서 하나라도 연장안된것여부를 보는거니까(전부 (취소포함) 출결사항이 있으면 연장이필요한거로 판단되는거구만! 이제 이해했다.

No_Status로 만 바꾸면 될듯해요

2023-07-19 12:41 UTC, sojungpp commented on src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
> +        boolean isMissingMaintenance = scheduleRepository.existsByLessonInAndStatusNot(lessonList, ScheduleStatus.CANCEL);
- 7/1 O 레슨1
- 7/2 O 레슨1
- 7/3 O 레슨2
- 7/4 X 레슨2
=> true

잊지않겠어..* 로직 고민 같이 해준 슈슈 감사합니다 love U

2023-07-19 13:16 UTC, YuSuhwa-ve approved these changes
아자앚아아자

2023-07-19 13:16 UTC, YuSuhwa-ve commented on src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
> +            if(isMissingMaintenance) break;
당신은 쵝오 입니다.

2023-07-19 13:16 UTC, merged